#!/bin/sh

case $1 in

    start)
        start-stop-daemon -S -n aesdsocket -a /bin/aesdsocket -- -d
        Ret=0
    ;;

    stop)
        start-stop-daemon -K -n aesdsocket 
        Ret=0
    ;;

    *)
        echo "Use: $(basename $0) start|stop"
        Ret=1
    ;;
esac

exit ${Ret}

